[package]
name = "codeql-extractor-action"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.11"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
thiserror = "2"
dotenvy = "0.15"
# Actions
ghactions = { version = "0.13", features = ["dotenvy", "generate", "octocrab"] }
# GitHub API
octocrab = "0.43"
