name: "Test Self Action"

on:
  push:
    branches: [ main ]

env:
  EXTRACTOR_REPOSITORY: advanced-security/codeql-extractor-iac

jobs:
  action-test:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Run the action"
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          extractor_repository: ${{ env.EXTRACTOR_REPOSITORY }}

