name: "Test Self Action"

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  EXTRACTOR_REPOSITORY: advanced-security/codeql-extractor-iac

jobs:
  action-test:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Run the action"
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          extractor: ${{ env.EXTRACTOR_REPOSITORY }}

